
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shariftest
    restart: always
    ports:
      - "3000:3000"
    working_dir: /usr/src/app





