from jenkinsci/jenkins:lts

USER root
RUN apt-get update -qq \
    && apt-get install -qqy apt-transport-https ca-certificates curl gnupg2 software-properties-common  python-pip

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
RUN apt-get update  -qq \
    && apt-get install docker-ce=17.12.1~ce-0~debian -y

RUN usermod -aG docker jenkins
RUN curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose --insecure

RUN pip install docker-compose
RUN chmod +x /usr/local/bin/docker-compose


## Run two in one  container
## First Need to clone the git and add the Volume
#WORKDIR /DevOps-Test/myapp/
#VOLUME . /DevOps-Test/myapp/
#ENTRYPOINT ["/DevOps-Test/myapp/main.sh"]


